parameters:
    cache_dsn: '%env(CACHE_DSN)%'

services:
    cache.redis:
        public: true
        class: Symfony\Component\Cache\Adapter\RedisAdapter
        parent: cache.adapter.redis
        tags:
            -   name: cache.pool
                clearer: cache.app_clearer
                provider: 'redis://%cache_dsn%'
                namespace: 'uk-covid19-test-providers'
