name: app
type: php:7.4
disk: 1024
build:
    flavor: composer
dependencies:
    php:
        composer/composer: '^2'
mounts:
    var/cache:
        source: local
        source_path: cache
    var/log:
        source: local
        source_path: log
    var/data:
        source: local
        source_path: data
web:
    locations:
        /:
            root: public
            index:
                - index.html