.app: &app
    type: upstream
    upstream: app:http
    cache:
        enabled: false
    ssi:
        enabled: false

https://{default}/: *app

https://master-7rqtwti-f2dppennkuoja.uk-1.platformsh.site:
    type: redirect
    to: "https://ukcovidtests.ccplatform.net"